import type { BrandArchetype, BrandArchetypeDefinition } from "@/server/domain/branding/brand-tokens";

export const BRAND_ARCHETYPES: Record<BrandArchetype, BrandArchetypeDefinition> = {
  minimal_nude: {
    label: "Minimal Nude",
    defaultFontPair: "playfair_jakarta",
    light: {
      background: "#fff8f5",
      foreground: "#1e1b19",
      card: "#faf2ee",
      cardForeground: "#1e1b19",
      popover: "#ffffff",
      popoverForeground: "#1e1b19",
      primary: "#72564c",
      primaryForeground: "#ffffff",
      secondary: "#e2e2e2",
      secondaryForeground: "#636564",
      muted: "#f4ece8",
      mutedForeground: "#504441",
      accent: "#cca730",
      accentForeground: "#4f3d00",
      destructive: "#ba1a1a",
      border: "#d4c3be",
      input: "#d4c3be",
      ring: "#72564c",
      radius: "0.5rem",
    },
    dark: {
      background: "#1e1b19",
      foreground: "#f7efeb",
      card: "#262220",
      cardForeground: "#f7efeb",
      popover: "#211d1a",
      popoverForeground: "#f7efeb",
      primary: "#e4beb2",
      primaryForeground: "#2b160f",
      secondary: "#3a3c3b",
      secondaryForeground: "#e2e2e2",
      muted: "#2c2723",
      mutedForeground: "#cbb9b2",
      accent: "#e9c349",
      accentForeground: "#241a00",
      destructive: "#ffb4ab",
      border: "#504441",
      input: "#504441",
      ring: "#e4beb2",
      radius: "0.5rem",
    },
  },
  glam: {
    label: "Glam",
    defaultFontPair: "dmserif_outfit",
    light: {
      background: "#fff8f5",
      foreground: "#1e1b19",
      card: "#ffffff",
      cardForeground: "#1e1b19",
      popover: "#ffffff",
      popoverForeground: "#1e1b19",
      primary: "#d81b60",
      primaryForeground: "#ffffff",
      secondary: "#f3e5f5",
      secondaryForeground: "#4a1942",
      muted: "#fce4ec",
      mutedForeground: "#6b3a4a",
      accent: "#cca730",
      accentForeground: "#241a00",
      destructive: "#ba1a1a",
      border: "#eab3c9",
      input: "#eab3c9",
      ring: "#d81b60",
      radius: "0.5rem",
    },
    dark: {
      background: "#1a1013",
      foreground: "#fce4ec",
      card: "#241820",
      cardForeground: "#fce4ec",
      popover: "#1f151a",
      popoverForeground: "#fce4ec",
      primary: "#f48fb1",
      primaryForeground: "#3a0d1e",
      secondary: "#3a2430",
      secondaryForeground: "#f3e5f5",
      muted: "#2c1c22",
      mutedForeground: "#d8a8bc",
      accent: "#e9c349",
      accentForeground: "#241a00",
      destructive: "#ffb4ab",
      border: "#4a2e38",
      input: "#4a2e38",
      ring: "#f48fb1",
      radius: "0.5rem",
    },
  },
  editorial: {
    label: "Editorial",
    defaultFontPair: "jakarta_solo",
    light: {
      background: "#ffffff",
      foreground: "#111111",
      card: "#ffffff",
      cardForeground: "#111111",
      popover: "#ffffff",
      popoverForeground: "#111111",
      primary: "#111111",
      primaryForeground: "#ffffff",
      secondary: "#e5e5e5",
      secondaryForeground: "#111111",
      muted: "#f2f2f2",
      mutedForeground: "#555555",
      accent: "#111111",
      accentForeground: "#ffffff",
      destructive: "#ba1a1a",
      border: "#111111",
      input: "#111111",
      ring: "#111111",
      radius: "0rem",
    },
    dark: {
      background: "#0d0d0d",
      foreground: "#f5f5f5",
      card: "#0d0d0d",
      cardForeground: "#f5f5f5",
      popover: "#0d0d0d",
      popoverForeground: "#f5f5f5",
      primary: "#f5f5f5",
      primaryForeground: "#0d0d0d",
      secondary: "#262626",
      secondaryForeground: "#f5f5f5",
      muted: "#1a1a1a",
      mutedForeground: "#a3a3a3",
      accent: "#f5f5f5",
      accentForeground: "#0d0d0d",
      destructive: "#ffb4ab",
      border: "#f5f5f5",
      input: "#f5f5f5",
      ring: "#f5f5f5",
      radius: "0rem",
    },
  },
  pastel_soft: {
    label: "Pastel Soft",
    defaultFontPair: "fraunces_nunito",
    light: {
      background: "#fdf6f9",
      foreground: "#3a2e35",
      card: "#ffffff",
      cardForeground: "#3a2e35",
      popover: "#ffffff",
      popoverForeground: "#3a2e35",
      primary: "#9a59aa",
      primaryForeground: "#ffffff",
      secondary: "#cdeadb",
      secondaryForeground: "#1f4d38",
      muted: "#f5e6ee",
      mutedForeground: "#79636f",
      accent: "#ffd9a0",
      accentForeground: "#6b4a12",
      destructive: "#d33632",
      border: "#f0d9e6",
      input: "#f0d9e6",
      ring: "#9a59aa",
      radius: "1.5rem",
    },
    dark: {
      background: "#241f26",
      foreground: "#f3e9f0",
      card: "#2e2830",
      cardForeground: "#f3e9f0",
      popover: "#2a242c",
      popoverForeground: "#f3e9f0",
      primary: "#d3a9dd",
      primaryForeground: "#2e123a",
      secondary: "#2f4a3c",
      secondaryForeground: "#cdeadb",
      muted: "#332b36",
      mutedForeground: "#c7b8c3",
      accent: "#e8b871",
      accentForeground: "#3a2708",
      destructive: "#ff8f8a",
      border: "#453b49",
      input: "#453b49",
      ring: "#d3a9dd",
      radius: "1.5rem",
    },
  },
};
